name: Build with nix and create docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  REGISTRY: ghcr.io

jobs:
  evaluate:
    name: Make sure that the nix flake evaluates and run the checks; then build docker image from flake and push it to registry.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            auto-optimise-store = false
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          swap-storage: false
          tool-cache: true
      - name: Set flake lockfile policy
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "NIX_FLAKE_FLAGS=--no-update-lock-file" >> "$GITHUB_ENV"
          else
            echo "NIX_FLAKE_FLAGS=" >> "$GITHUB_ENV"
          fi
      - run: nix build $NIX_FLAKE_FLAGS .\#nemo
      - run: nix build $NIX_FLAKE_FLAGS .\#nemo-language-server
      - run: nix build $NIX_FLAKE_FLAGS .\#nemo-python
      - run: nix build $NIX_FLAKE_FLAGS .\#nemo-wasm-bundler
      - run: nix build $NIX_FLAKE_FLAGS .\#nemo-wasm-node
      - run: nix build $NIX_FLAKE_FLAGS .\#nemo-wasm-web
      - run: nix build $NIX_FLAKE_FLAGS .\#nemo-vscode-extension
      - run: nix build $NIX_FLAKE_FLAGS .\#nemo-web
      - run: nix build $NIX_FLAKE_FLAGS .\#nemo-doc
      - run: nix flake check $NIX_FLAKE_FLAGS
      - name: Build and Collect garbage
        run: |
          nix build $NIX_FLAKE_FLAGS .\#{nemo{,-doc,-language-server,-python,-vscode-extension,-wasm-bundler,-wasm-node,-wasm-web,-web},docker}
          nix-store --optimise
          nix-collect-garbage -d

      - name: Log in to the Container registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: |
          nix build $NIX_FLAKE_FLAGS .\#docker
          docker load < result
          docker image tag nemo:latest ${{ env.REGISTRY }}/${{ github.repository_owner }}/nemo:latest
      - name: Push docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/nemo:latest
