name: CI PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test Rust ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { rust: nightly, os: ubuntu-latest }
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test --verbose

  clippy:
    name: Lint with clippy
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: nightly
      - run: cargo clippy --all-targets --workspace --verbose

  rustfmt:
    name: Verify code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: nightly
      - run: cargo fmt --all -- --check

  doc:
    name: Verify crate documentation
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - run: cargo doc --workspace

  miri:
    name: Check for undefined behaviour with miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: miri
          toolchain: nightly
      - run: cargo miri setup
      - run: cargo miri test -- -Z unstable-options --report-time

  test-python:
    name: Test python bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: build python bindings
        uses: PyO3/maturin-action@v1
        with:
          working-directory: "nemo-python"
      - name: install python bindings
        run: ls target/wheels/*.whl | xargs pip install
      - name: run python tests
        run: python -m unittest discover -s nemo-python/tests -v

  pycodestyle:
    name: Check python code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: install pycodestyle
        run: pip install pycodestyle
      - name: run pycodestyle
        run: pycodestyle nemo-python

  wasm-pack:
    name: Test wasm bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: wasm-pack test --headless --chrome nemo-wasm
      - run: wasm-pack test --headless --firefox nemo-wasm

  nix-and-docker:
    name: Verify nix flake and docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            auto-optimise-store = false
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          swap-storage: false
          tool-cache: true
      - run: nix build .\#nemo
      - run: nix build .\#nemo-language-server
      - run: nix build .\#nemo-python
      - run: nix build .\#nemo-wasm-bundler
      - run: nix build .\#nemo-wasm-node
      - run: nix build .\#nemo-wasm-web
      - run: nix build .\#nemo-vscode-extension
      - run: nix build .\#nemo-web
      - run: nix build .\#nemo-doc
      - run: nix flake check
      - name: Build and collect garbage
        run: |
          nix build .\#{nemo{,-doc,-language-server,-python,-vscode-extension,-wasm-bundler,-wasm-node,-wasm-web,-web},docker}
          nix-store --optimise
          nix-collect-garbage -d
      - name: Build docker image
        run: |
          nix build .\#docker
          docker load < result
